// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBplyJ244NfRt6Iik6OLQhzJsOmtWUOXTk',
    appId: '1:225848042220:android:1da67313504fdf71397bc9',
    messagingSenderId: '225848042220',
    projectId: 'syria-pharmacy-ce885',
    storageBucket: 'syria-pharmacy-ce885.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuZ2e4CHwKal6Brg5ApMCuLC7wZD-FSA0',
    appId: '1:225848042220:ios:8b9734c6a7d0480c397bc9',
    messagingSenderId: '225848042220',
    projectId: 'syria-pharmacy-ce885',
    storageBucket: 'syria-pharmacy-ce885.firebasestorage.app',
    androidClientId: '225848042220-amehj6o4f1vd5h62jgfclv0k6mosopa8.apps.googleusercontent.com',
    iosClientId: '225848042220-30cj50mlhten3t2appg4hqccqb0siuap.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.sixvalley.seller-seller',
  );
}
